### ISSUE TITLE
Access to the path '*\AppData\Roaming\PlexampRPC\auth' is denied.

### ISSUE THREAD

**Issue by billwhy** [Dyvinia/PlexampRPC#1]
**When running the .exe it doesn't create the *\AppData\Roaming\PlexampRPC\auth directory, so I manually created the directory and received this error:**

```
Access to the path '*\AppData\Roaming\PlexampRPC\auth' is denied.


at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)

at [Microsoft.Win32.SafeHandles.SafeFileHandle.Open](https://microsoft.win32.safehandles.safefilehandle.open/)(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable\1 unixCreateMode)`

at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)

at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)

at PlexampRPC.App.PlexSignIn(Boolean resignIn) in D:\Development\repos\PlexampRPC\App.xaml.cs:line 93

at PlexampRPC.App.OnStartup(StartupEventArgs e) in D:\Development\repos\PlexampRPC\App.xaml.cs:line 75

at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by Dyvinia** [comment]
Can you try with this
[PlexampRPC.zip](https://github.com/Dyvinia/PlexampRPC/files/11360414/PlexampRPC.zip)

**Comment by billwhy** [comment]
This fixed it! Thanks for resolving this so promptly!

![image](https://user-images.githubusercontent.com/21093478/235332430-fcfd7588-a1fd-4407-be56-99aa8caad4c4.png)

**Comment by STRHercules** [comment]
Same issue, I tried the new .exe you linked above and got this error: 

```
Could not find a part of the path 'C:\Users\zkais\AppData\Roaming\PlexampRPC\auth.token'.

   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.File.OpenHandle(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.File.WriteToFile(String path, FileMode mode, String contents, Encoding encoding)
   at PlexampRPC.App.PlexSignIn(Boolean resignIn) in D:\Development\repos\PlexampRPC\App.xaml.cs:line 93
   at PlexampRPC.App.OnStartup(StartupEventArgs e) in D:\Development\repos\PlexampRPC\App.xaml.cs:line 75
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   ```

**Comment by Dyvinia** [comment]
I think I might've made a silly mistake, try this to see if its fixed
[PlexampRPC.zip](https://github.com/Dyvinia/PlexampRPC/files/11360459/PlexampRPC.zip)

**Comment by STRHercules** [comment]
That fixed it for me!

**Comment by Dyvinia** [comment]
Does this work 
[PlexampRPC.zip](https://github.com/Dyvinia/PlexampRPC/files/11360497/PlexampRPC.zip)

**Comment by STRHercules** [comment]
Negative, but it seems I was wrong in why it crashed earlier. Seems like its time based? I was able to select my server but it crashed shortly after. Same result no matter how many times I switch servers

**Comment by Dyvinia** [comment]
it seems it just can't connect to any servers, is the server accessable outside the network? (or maybe a firewall or something)

**Comment by STRHercules** [comment]
Yeah I have numerous users who live all over the country who have no issues

**Comment by Dyvinia** [comment]
Try the latest version, It doesn't solve issues with connecting but it should resolve crashes if it fails. Also closing this issue as the main issue is resolved, the connection issue has a new issue at #2
