### ISSUE TITLE
Nothing showing in Discord

### ISSUE THREAD

**Issue by roxaloxa** [Dyvinia/PlexampRPC#12]
Plex connected just fine, log starts fine

```
[14:50:14] Connected to roxaloxa's Discord Client
[14:50:14] StatusCode: OK. Request Uri: https://plex.tv/api/v2/user.json/
[14:50:15] StatusCode: OK. Request Uri: https://plex.tv/pms/servers.xml/
```

then shows this on every interval:
```
[14:50:17] WARN: Unable to get current session: No connection could be made because the target machine actively refused it. (157.211.239.241:28665) System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
```

Latest Discord, Windows 10, latest PlexampRPC release.

**Comment by Dyvinia** [comment]
do you think you could retry this on the lates version?

**Comment by roxaloxa** [comment]
A second or two after launching the latest version, I get:

```
Invalid URI: The format of the URI could not be determined.

   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at PlexampRPC.MainWindow.UpdateAccountIcon() in PlexampRPC\Windows\MainWindow.xaml.cs:line 99
   at PlexampRPC.App.OnStartup(StartupEventArgs e) in PlexampRPC\App.xaml.cs:line 94
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

and then a browser page opens for me to log-in. I log in, restart the app and it takes me in and loads my user up, but the log is spamming like:

![image](https://github.com/user-attachments/assets/158d16a3-2aba-4392-b625-4f72ecc03ec0)

and I get no presence in Discord.
