### ISSUE TITLE
App crashes (possibly because artist name is too long?)

### ISSUE THREAD

**Issue by eirise** [Dyvinia/PlexampRPC#7]
I'm getting this error. Not sure why, but the artist name is significantly long - 58 Japanese characters, so it could be that?

Artist name is ```ガヴリール(CV:富田美憂)、ヴィーネ(CV:大西沙織)、サターニャ(CV:大空直美)、ラフィエル(CV:花澤香菜)```, song name is ```ハレルヤ☆エッサイム (instrumental)```, album name is ```ハレルヤ☆エッサイム```

However, it works fine with a different song with artist name as  ```サターニャ(CV:大空直美)、ラフィエル(CV:花澤香菜)```

```
State

   at DiscordRPC.BaseRichPresence.set_State(String value)
   at PlexampRPC.MainWindow.SetPresence(PresenceData presence) in D:\Development\repos\PlexampRPC\Windows\MainWindow.xaml.cs:line 176
   at PlexampRPC.MainWindow.StartPolling() in D:\Development\repos\PlexampRPC\Windows\MainWindow.xaml.cs:line 118
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

**Comment by eirise** [comment]
I think I found the issue, Discord rich presence only accepts a max of 128 bytes for strings and the artist name I mentioned is [134 bytes (in UTF-8 encoding)](https://mothereff.in/byte-counter).

Would it be possible to add a check for if strings are >128 bytes, and if so, truncate them?

**Comment by includenull** [comment]
I also had the same issue today but I think it was a track name being too long.

```State

   at DiscordRPC.BaseRichPresence.set_State(String value)
   at PlexampRPC.MainWindow.SetPresence(PresenceData presence) in D:\Development\repos\PlexampRPC\Windows\MainWindow.xaml.cs:line 197
   at PlexampRPC.MainWindow.StartPolling() in D:\Development\repos\PlexampRPC\Windows\MainWindow.xaml.cs:line 118
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)```

**Comment by Dyvinia** [comment]
Should be fixed now
